name: external-prs-check

on:
  pull_request:
    types: [ opened, synchronize ]

jobs:
  check-build:
    if: github.event.pull_request.head.repo.fork
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive  # Fetch private content
        fetch-depth: 1         # Fetch all history for .GitInfo and .Lastmod
        lfs: true

    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: '22'

    - name: 🔨 Build project
      env:
        VITE_GITHUB_URL: https://github.com/cardano-foundation/cf-explorer-landing
        VITE_CARDANO_URL: https://cardano.org/
      run: |
        npm ci
        npm run build
